### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by VashSan** [VashSan/wishmaster#20]
A new follower occurred... and with it a crash:

TypeError: Cannot read property 'toString' of undefined
    at c:\Users\Vash\Documents\Wishmaster\src\shared\Database.ts:250:45
    at Array.forEach (<anonymous>)
    at UserCollection.assembleResult (c:\Users\Vash\Documents\Wishmaster\src\shared\Database.ts:249:14)
    at c:\Users\Vash\Documents\Wishmaster\src\shared\Database.ts:241:43
    at newArguments.<computed> (c:\Users\Vash\Documents\Wishmaster\node_modules\nedb\lib\executor.js:29:17)
    at Cursor.execFn (c:\Users\Vash\Documents\Wishmaster\node_modules\nedb\lib\datastore.js:484:12)
    at callback (c:\Users\Vash\Documents\Wishmaster\node_modules\nedb\lib\cursor.js:126:19)
    at c:\Users\Vash\Documents\Wishmaster\node_modules\nedb\lib\cursor.js:193:12
    at c:\Users\Vash\Documents\Wishmaster\node_modules\nedb\lib\datastore.js:329:14
    at Object.async.eachSeries (c:\Users\Vash\Documents\Wishmaster\node_modules\async\lib\async.js:130:20)

**Comment by VashSan** [comment]
fixed with d62cb5fed5f1801600a5af4b9ca3a6ae35b1c7e0
