### ISSUE TITLE
Crash occurred on new follower

### ISSUE THREAD

**Issue by VashSan** [VashSan/wishmaster#22]
TypeError: Cannot read property 'followDate' of null
    at C:\Users\Vash\Documents\Wishmaster\src\shared\Database.js:131:21
    at newArguments.<computed> (C:\Users\Vash\Documents\Wishmaster\node_modules\nedb\lib\executor.js:29:17)
    at Cursor.execFn (C:\Users\Vash\Documents\Wishmaster\node_modules\nedb\lib\datastore.js:520:14)
    at callback (C:\Users\Vash\Documents\Wishmaster\node_modules\nedb\lib\cursor.js:126:19)
    at C:\Users\Vash\Documents\Wishmaster\node_modules\nedb\lib\cursor.js:193:12
    at C:\Users\Vash\Documents\Wishmaster\node_modules\nedb\lib\datastore.js:329:14
    at Object.async.eachSeries (C:\Users\Vash\Documents\Wishmaster\node_modules\async\lib\async.js:130:20)
    at C:\Users\Vash\Documents\Wishmaster\node_modules\nedb\lib\datastore.js:323:11
    at fn (C:\Users\Vash\Documents\Wishmaster\node_modules\async\lib\async.js:582:34)
    at Immediate.<anonymous> (C:\Users\Vash\Documents\Wishmaster\node_modules\async\lib\async.js:498:34)

**Comment by VashSan** [comment]
fixed by 7cca6d3b4ae6d6295aaafea0b981e85744ab7f45
